### ISSUE TITLE
Dashboard - Customise this page buttonplacment, Stop customising button hidden

### ISSUE THREAD

**Issue by beloit-rexj** [kennibc/moodle-theme_evolved#7]
Hello,

The "customise this page" button appears to be very low and is covering up the black line-arrow graphic. Is the button supposed to be that low?

When a user customizes a dashboard page the "Stop customizing this page" button is hidden by any blocks in the main region. If the user docks all the blocks in the main region then the button is visible. This seems like a bug. I think that placemnet in the upper right corner across from the breadcrumbs is good. If that is not possible, then I suggest that the buttons be above the main region area.

**Comment by kennibc** [comment]
I got a fix for this. 

Delete this in evolved.css ~line 619
#editbutton {
  float: right;
}

add this to same file:
.singlebutton div {float:right;}

This will make the buttons in a single line.

**Comment by kennibc** [comment]
I will include this fix in the next release.

**Comment by beloit-rexj** [comment]
Thank you!

**Comment by kennibc** [comment]
Actually one small change.  
This is more specific just to those buttons.  

#editbutton .singlebutton div {float:right;}

**Comment by kennibc** [comment]
Please test and verify the #editbutton .singlebutton div {float:right;}  added to evolved.css works.  I tried it on my dev and production server and this does seem to fix the issue.  

The reason .singlebutton div {float:right;} doesn't work is on other pages the button goes to the right giving undesired results.  Example with a Quiz if you do a preview the "Start a new preview" button goes to the far right of the screen.

Please test and verify   
#editbutton .singlebutton div {float:right;} 
works.

Thanks.

**Comment by beloit-rexj** [comment]
I am attempting to test, but have a question.

Not trying to be difficult, but I downloaded a fresh copy of the theme from
git and opened the evolved.css file. I cannot find
#editbutton {
float: right;
}
anywhere. There are only 467 lines of code in the file I am looking at. Am
I missing something?

Thanks

**Comment by beloit-rexj** [comment]
Weird. I open the file in Notepad++ and get 469 lines. I edit the file on
the server in VIM and find what you mention. Hmmmm.

**Comment by beloit-rexj** [comment]
The code change worked on my system. The buttons appear above the block now. They are positioned on the left hand side of the main content region.
![mdl 29 evolved dashboard edit button](https://cloud.githubusercontent.com/assets/9689055/8706875/c9643c28-2af7-11e5-9ac1-b0b6b0a78913.png)

**Comment by kennibc** [comment]
Add these lines:
#editbutton .btn {float: right;}
#editbutton .singlebutton div {float:right;}

Delete this line:  
#editbutton {
float: right;
}

Adding this to evolved.css will address the issue.  I am just testing right now to make sure no other buttons are affected.  

I am going to package it up and put it on Moodle.org next week.  

Just to verify, this is the Moodle 2.8 version of the evolve-D theme.

**Comment by kennibc** [comment]
/* evolved CSS
-------------------------*/

#dock {background: #32352c; }

#page-header {
  margin-top:5px;
  margin-bottom: 35px;
}

#page-footer {
  border-top: 0px;
}

.arrow {color: #3d3d3d; }

.block .header h2 {color: #3d3d3d;}

.pagelayout-report .no-overflow {
overflow: auto;
}

/* Tab Navigation */
.nav-tabs {
    margin: 0px;
    padding: 0px;
    border: 0px;    
}
.nav-tabs > li > a {
    background: #DADADA;
    border-radius: 0;
    box-shadow: inset 0 -8px 7px -9px rgba(0,0,0,.4),-2px -2px 5px -2px rgba(0,0,0,.4);
}
.nav-tabs > li.active > a,
.nav-tabs > li.active > a:hover {
    background: #F5F5F5;
    box-shadow: inset 0 0 0 0 rgba(0,0,0,.4),-2px -3px 5px -2px rgba(0,0,0,.4);
}

/* Tab Content */
.entrybox {
    background: #F5F5F5;
    box-shadow: 0 0 4px rgba(0,0,0,.4);
    border-radius: 0;
    text-align: center;
    padding-top: 15px;
}

/********Frontpage**********/
.service {
	display:block;
	padding:10px;
	margin: 10px;
	text-align:left;
  background-color: [[setting:marketboxcolor]];
	-webkit-border-radius:4px;
	-moz-border-radius:4px;
	border-radius:4px;
}


#fullbkg { 
   background: url([[setting:fpbkg]]) no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}


/*Frontpage Login*/
.wrap {
	width:250px;
	height: auto;
	margin: auto;
	margin-top: 10%;
	margin-bottom: 3%;
}
.avatarlogin {
	width: 100%;
	margin: auto;
	width: 65px;
	border-radius: 100px;
	height: 65px;
	background: #000 ;
	position: relative;
	bottom: -15px;
}
.avatarlogin img {
	width: 55px;
	height: 55px;
	border-radius: 100px;
	margin: auto;
	border:3px solid #fff;
	display: block;
}
.wrap input {
	border: none;
	background: #fff;
  font-family:Lato ;
  font-weight:700 ;
	display: block;
	height: 40px;
	outline: none;
	width: calc(100% - 24px) ;
	margin: auto;
	padding: 6px 12px 6px 12px;
}
.bar {
	width: 100%;
	height: 1px;
	background: #fff ;
}
.bar i {
	width: 95%;
	margin: auto;
	height: 1px ;
	display: block;
	background: #d1d1d1;
}
.wrap input[type="text"] {
	border-radius: 7px 7px 0px 0px ;
}
.wrap input[type="password"] {
	border-radius: 0px 0px 7px 7px ;
}
.forgot_link {
	color: #83afdf ;
	color: #83afdf;
	text-decoration: none;
	font-size: 11px;
	position: relative;
	left: 193px;
	top: -36px;
}
.wrap button {
	width: 100%;
	border-radius: 7px;
	background: #b6ee65;
	text-decoration: center;
	border: none;
	color: #51771a;
  margin-top:-5px;
	padding-top: 14px;
	padding-bottom: 14px;
	outline: none;
	font-size: 20px;	
	border-bottom: 3px solid #307d63;
	cursor: pointer;
}

.loginbox h2{
color: #DBDBDB;
text-align:center;
}

.loginbox form a{
color: #fff;
}
.loginbox form{
color: #fff;
}
.loginbox .signuppanel .subcontent {
color: #fff;
}
.loginpanel .loginsub {
background: rgba(0,0,0,.8);
max-width:400px;
-webkit-box-shadow: 1px 0px 29px 14px rgba(255,255,255,0.6);
-moz-box-shadow: 1px 0px 29px 14px rgba(255,255,255,0.6);
box-shadow: 1px 0px 29px 14px rgba(255,255,255,0.6);
-webkit-border-radius:10px;
-moz-border-radius:10px;
border-radius:10px;
border:5px solid #fff;
margin: auto;
padding:20px;
}
.signuppanel .subcontent{
background: rgba(0,0,0,.6);
max-width:400px;
-webkit-box-shadow: 1px 0px 29px 14px rgba(255,255,255,0.6);
-moz-box-shadow: 1px 0px 29px 14px rgba(255,255,255,0.6);
box-shadow: 1px 0px 29px 14px rgba(255,255,255,0.6);
-webkit-border-radius:10px;
-moz-border-radius:10px;
border-radius:10px;
border: 5px solid #fff;
margin: auto;
}


/* Alerts (aardvark) */
#page-header-generalalert {
    clear:both;
	display: block;
	color:#ff9f00;
	background-color:#fef8d2;
	padding:8px 35px 8px 14px;
	margin-bottom:20px;
	text-shadow:0 1px 0 rgba(255,255,255,0.5);
	border:1px solid #fde6af;
	-webkit-border-radius:4px;
	-moz-border-radius:4px;
	border-radius:4px;
}
#page-header-generalalert:before {
    background-color: #ff9f00;
    color: #FFFFFF;
    display: block;
    float: left;
    font-family: FontAwesome;
    font-size: 1.2em;
    height: 1.4em;
    margin-right: 0.5em;
    margin-top: -0.15em;
	margin-left: -0.5em;
    padding-top: 0.2em;
    text-align: center;
    width: 1.7em;
	content:"\f06a";
	border-radius: 3px 3px 3px 3px;
	text-shadow:none;
}
#page-header-snowalert {
    clear:both;
	display: block;
	color:#3a87ad;
	background-color:#d9edf7;
	padding:8px 35px 8px 14px;
	margin-bottom:20px;
	text-shadow:0 1px 0 rgba(255,255,255,0.5);
	border:1px solid #bce8f1;
	-webkit-border-radius:4px;
	-moz-border-radius:4px;
	border-radius:4px;
}
#page-header-snowalert:before {
    background-color: #3a87ad;
    color: #FFFFFF;
    display: block;
    float: left;
    font-family: FontAwesome;
    font-size: 1.2em;
    height: 1.4em;
    margin-right: 0.5em;
    margin-top: -0.15em;
	margin-left: -0.5em;
    padding-top: 0.2em;
    text-align: center;
    width: 1.7em;
	content:"\f069";
	border-radius: 3px 3px 3px 3px;
	text-shadow:none;
}



/*Google Fonts (Theme Essential)*/

/* @group Headings */
h1, h2, h3, h4, h5, h6,
.back-to-top,
.socials p,
#socialheading,
.forumpost .subject,
.block_login label {
    font-family: "[[setting:headingfont]]", sans-serif;
}
/* @group Main Text */
body,
.block_login input[type="submit"] {
    font-family: "[[setting:bodyfont]]", Arial, Helvetica, sans-serif;
    font-size: [[setting:bodysize]];
    font-weight: [[setting:bodyweight]];
}
/* @end */

/*Special thanks to Shaun Daubney (Theme Aardvark)
for the colored icons in the blocks.
 */
.block .header .title h2:before {
    color: #FFFFFF;
    display: block;
    float: left;
    font-family: FontAwesome;
    font-size: 1.2em;
    height: 1.3em;
    margin-left: -0.5em;
    margin-right: 0.5em;
    margin-top: -0.2em;
    padding-top: 0.2em;
    text-align: center;
    width: 1.5em;
	-webkit-border-radius:2px;
	-moz-border-radius:2px;
	border-radius:2px;
}

.block_news_items .header .title h2:before {
    background-color: #29A294;
	content:"\f0a1";
}

.block_navigation .header .title h2:before {
    background-color: #f42941;
    content:"\f0e8";
}

.block_calendar_upcoming .header .title h2:before,
.block_calendar_month .header .title h2:before {
    background-color: #008ecd;
	content:"\f073";
}

.block_course_list .header .title h2:before {
    background-color: #ffce00;
	content:"\f108";
}

.block_completionstatus .header .title h2:before,
.block_selfcompletion .header .title h2:before {
    background-color: #76b900;
	content:"\f0e4";
}

.block_rss_client .header .title h2:before {
    background-color: #ff9500;
	content:"\f09e";
}

.block_rss_plus .header .title h2:before {
    background-color: #ff9500;
	content:"\f09e";
}

.block_blog_menu .header .title h2:before {
    background-color: #ff9500;
	content:"\f02d";
}

.block_quiz_results .header .title h2:before {
    background-color: #76b900;    
	content:"\f080";
}

.block_quiz_navblock .header .title h2:before {
    background-color: #76b900;
    content:"\f126";
}

.block_glossary_random .header .title h2:before {
    background-color: #3d3d3d;
    content:"\f0eb";
}

.block_book_toc .header .title h2:before {
    background-color: #3d3d3d;
    content:"\f02d";
}


.block_participants .header .title h2:before,
.block_online_users .header .title h2:before {
    background-color: #92499e;
    content:"\f0c0";
}

.block_html .header .title h2:before {
    background-color: #eeeeee;

}

.block_section_links .header .title h2:before {
    background-color: #f42941;
    content:"\f02e";
}

.block_activity_modules .header .title h2:before {
    background-color: #f42941;
    content:"\f12e";
}

.block_comments .header .title h2:before {
    background-color: #ffce00;
    content:"\f075";
}

.block_settings .header .title h2:before,
.block_admin_bookmarks .header .title h2:before{
    background-color: #004675;
    content:"\f085";
}

.block_blog_tags .header .title h2:before,
.block_tags .header .title h2:before {
    background-color: #ff9f00;
    content:"\f02c";
}

.block_private_files .header .title h2:before {
    background-color: #82cadd;
    content:"\f114";
}

.block_block_mentees .header .title h2:before {
    background-color: #3d3d3d;
    content:"\f0c0";
}

.block_messages .header .title h2:before {
    background-color: #ffce00;
    content:"\f0e0";
}

.block_community .header .title h2:before {
    background-color: #ffce00;
    content:"\f0ac";
}

.block_login .header .title h2:before {
    background-color: #3d3d3d;
    content:"\f007";
}

.block_recent_activity .header .title h2:before {
    background-color: #cee3ed;
    content:"\f017";
}

.block_search_forums .header .title h2:before {
    background-color: #ffce00;
    content:"\f0e6";
}

.block_myprofile .header .title h2:before {
    background-color: #f42941;
    content:"\f007";
}

.block_adminblock .header .title h2:before {
    background-color: #E0F52A;
    content:"\f055";
}

.block_feedback .header .title h2:before {
    background-color: #ffce00;
    content:"\f087";
}

.block_flickr .header .title h2:before {
    background-color: #ff3096;
    content:"\f03e";
}

.block_youtube .header .title h2:before {
    background-color: #f42941;
    content:"\f145";
}

.block_course_badges .header .title h2:before {
    background-color: #29a294;
    content:"\f091";
}

.block_twitter_search .header .title h2:before {
    background-color: #008ecd;
    content:"\f099";
}

.block_heritage .header .title h2:before {
    background-color: #3e647e;
    content:"\f02d";
}

.block_lrc .header .title h2:before {
    background-color: #3e647e;
    content:"\f02d";
}


/*box shadows */
@media screen{
.block, .service {
  	position:relative;       
    -webkit-box-shadow:0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
       -moz-box-shadow:0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
            box-shadow:0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
}

.block:before, .block:after, .service:before, .service:after {
content:"";
   position:absolute; 
    z-index:-1;
    -webkit-box-shadow:0 0 20px rgba(0,0,0,0.8);
    -moz-box-shadow:0 0 20px rgba(0,0,0,0.8);
    box-shadow:0 0 20px rgba(0,0,0,0.8);
    top:50%;
    bottom:0;
    left:10px;
    right:10px;
    -moz-border-radius:100px / 10px;
    border-radius:100px / 10px;
}

#region-main
{
    position:relative;       
    -webkit-box-shadow:0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
       -moz-box-shadow:0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
            box-shadow:0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
}
#region-main:before, #region-main:after
{
  content:"";
    position:absolute; 
    z-index:-1;
    -webkit-box-shadow:0 0 20px rgba(0,0,0,0.8);
    -moz-box-shadow:0 0 20px rgba(0,0,0,0.8);
    box-shadow:0 0 20px rgba(0,0,0,0.8);
    top:50%;
    bottom:0;
    left:10px;
    right:10px;
    -moz-border-radius:100px / 10px;
    border-radius:100px / 10px;
}
}

/* BREADCRUMBS */
.breadcrumb-nav {  
  background-color:none;
}

.breadcrumb {
  display: inline-block;
  box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.35);
  overflow: hidden;
  border-radius: 5px;
  background-color:none;
margin:0px;
padding:0px;
background: none;
}
.breadcrumb a {
  color:white;
}

.breadcrumb li {
  text-decoration: none;
  outline: none;
  display: block;
  float: left;
  font-size: 14px;
  line-height: 36px;
  color: white;
  padding: 0 15px 0 30px;
  background: #666;
  background: linear-gradient(#666, #333);
  position: relative;
    background-color:none;
}

.breadcrumb li:first-child {
  padding-left: 25px;
  border-radius: 5px 0 0 5px;
}

.breadcrumb li:first-child:before {
  left: 14px;
}

.breadcrumb li:last-child {
  border-radius: 0 5px 5px 0;
  padding-right: 20px;
}

/*hover/active styles*/
.breadcrumb li.active, .breadcrumb li:hover{
  background: #333;
  background: linear-gradient(#333, #000);
}

.breadcrumb li.active:after, .breadcrumb li:hover:after {
  background: #333;
  background: linear-gradient(135deg, #333, #000);
}

.breadcrumb li:after {
  content: '';
  position: absolute;
  top: 0; 
  right: -18px;
  width: 36px; 
  height: 36px;
  transform: scale(0.707) rotate(45deg);
 z-index: 1;
  background: #666;
  background: linear-gradient(135deg, #666, #333);
  box-shadow: 
    2px -2px 0 2px rgba(0, 0, 0, 0.4), 
    3px -3px 0 2px rgba(255, 255, 255, 0.1);
  border-radius: 0 5px 0 50px;
}

.breadcrumb li:last-child:after {
  content: none;
}

.course-title {
  position: relative;
  border-bottom: 4px solid #000;
  margin-bottom: 30px;
  text-transform: uppercase;
  padding-left:15px;
  padding-right: 15px;
}

#editbutton .btn {float: right;}
#editbutton .singlebutton div {float:right;}

.course-title:after, .course-title:before {
  top: 100%;
  left: 50%;
  border: solid transparent;
  content: " ";
  height: 0;
  width: 0;
  position: absolute;
  pointer-events: none;
}

.course-title:after {
  border-color: rgba(136, 183, 213, 0);
  border-width: 20px;
  margin-left: -20px;
}
.course-title:before {
  border-color: rgba(194, 225, 245, 0);
  border-top-color: #000;
  border-width: 26px;
  margin-left: -26px;
}

#dndupload-status {
  position: fixed;
  left: 0;
  width: 40%;
  margin: 0 30%;
  padding: 6px;
  border: 1px solid #bce8f1;
  text-align: center;
  background: #d9edf7;
  color: #3a87ad;
  z-index: 100;
  -webkit-box-shadow: 2px 2px 5px 1px #ccc;
  -moz-box-shadow: 2px 2px 5px 1px #ccc;
  box-shadow: 2px 2px 5px 1px #ccc;
  -webkit-border-radius: 8px;
  -moz-border-radius: 8px;
  border-radius: 8px;
}

.user-enroller-panel {
  z-index: 2;
}

.fpcustomnav {
  display: inline-block;
  width:100%;
}

.fpicon {
  float: left;
  margin:0px;
  padding:0px;
  max-width:80px;
}
.fpsearch {
  float: right;
  display: inline-block;
  margin:5px;
  padding-right:10px;
}
.navicon {
  margin-right: 10px;
  padding:5px;
}

/*PRINT */
@media print {
body * {visibility: hidden;}
#region-main * {visibility: visible; display:block;}
#region-main { position: absolute; top: 40px; max-width:650px;}
.course-content {border:0px;}
}

/*Social Wall*/
.format-socialwall .course-content ul.topics li.section {
border-bottom: 0px solid #ccc;
margin-top: 0;
}
.format-socialwall #section-0 .content {
  display:none;
  visibility: hidden;
}
.format-socialwall #section-2 .content {
background-color: #f7f7f7;
padding: 10px;
margin: 0px;
border: 3px solid #d4d4d4;
border-radius: 4px;
margin-top:15px;
margin-bottom: 15px;
-moz-box-shadow: 0px 0px 25px #000;
-webkit-box-shadow: 0 0 25px #000;
box-shadow: 0px 0px 25px #000;
}

.format-socialwall .tl-post {
margin: 30px 0px 50px 0px;
padding:15px;
}

.format-socialwall .tl-posttext {
background-color: #F5F5F5;
padding: 10px 10px 20px 10px;
border-radius: 10px 10px 0px 0px;
border: 1px solid #ccc;
margin-top: 10px;
}

.format-socialwall ul.section.tl-postattachment {
background-color: #F6FAA0;
padding: 5px 5px 5px 50px;
border-left: 1px solid #ccc;
border-right: 1px solid #ccc;
margin:0px;
}

.format-socialwall ul.section.tl-postattachment:before {
  content: "\f0c6  Attachments";
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  margin-left:-15px;
  padding-bottom: 4px;
  border-bottom:2px solid #ccc;
}
.format-socialwall .tl-comments:before {
  content: "\f0e6  Comments";
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  padding-bottom: 4px;
  width:100%;
  text-align: center;
}

.format-socialwall .tl-posttext:before{
  content: "\f0e5  Message";
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  padding-bottom: 4px;
  border-bottom:2px solid #ccc;
  width:100%;
  text-align: center;
}

.format-socialwall .tl-post:before{
  content: "\f086  Post";
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 18px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  padding-bottom: 4px;
  padding-left:15px;
  text-align: center;
}

.format-socialwall .tl-text {
margin-left: 40px;
padding:10px;
border: 2px solid #efefef;
-moz-box-shadow: 0px 0px 25px #000;
-webkit-box-shadow: 0 0 25px #000;
box-shadow: 0px 0px 25px #000;
border-radius: 4px 4px 4px 4px;
background-color: #fff;
}

.format-socialwall .tl-comments {
padding:15px;
margin:0px;
}
.format-socialwall .tl-comments .tl-text {
  border: 2px solid #ccc;
  -moz-box-shadow: none;
  -webkit-box-shadow: none;
  box-shadow: none;
}
.format-socialwall .tl-comment {
padding-left:25px;
padding-top: 0px;
padding-bottom: 0px;
}

.format-socialwall .tl-post-actionarea {
border: 1px solid #ccc;
padding: 4px 4px 10px 4px;
background: #F0F3F7;
border-radius: 0px 0px 5px 5px;
}

.format-socialwall .tl-timeago, .tl-counts {
font-size: 12px;
color: #666;
line-height: 15px;
padding-bottom: 5px;
}

.format-socialwall .like {
   border-top: 1px solid #96d1f8;
   background: #65a9d7;
   background: -webkit-gradient(linear, left top, left bottom, from(#3e779d), to(#65a9d7));
   background: -webkit-linear-gradient(top, #3e779d, #65a9d7);
   background: -moz-linear-gradient(top, #3e779d, #65a9d7);
   background: -ms-linear-gradient(top, #3e779d, #65a9d7);
   background: -o-linear-gradient(top, #3e779d, #65a9d7);
   padding: 5px 5px;
   -webkit-border-radius: 8px;
   -moz-border-radius: 8px;
   border-radius: 8px;
   -webkit-box-shadow: rgba(0,0,0,1) 0 1px 0;
   -moz-box-shadow: rgba(0,0,0,1) 0 1px 0;
   box-shadow: rgba(0,0,0,1) 0 1px 0;
   text-shadow: rgba(0,0,0,.4) 0 1px 0;
   color: white;
   font-size: 14px;
   font-family: Georgia, serif;
   text-decoration: none;
   vertical-align: middle;
   }

.format-socialwall .like:hover {
   border-top-color: #28597a;
   background: #28597a;
   color: #ccc;
   }

.format-socialwall .like:active {
   border-top-color: #1b435e;
   background: #1b435e;
   }

.format-socialwall .likenomore {
   border-top: 1px solid #96d1f8;
   background: #65a9d7;
   background: -webkit-gradient(linear, left top, left bottom, from(#3e779d), to(#65a9d7));
   background: -webkit-linear-gradient(top, #3e779d, #65a9d7);
   background: -moz-linear-gradient(top, #3e779d, #65a9d7);
   background: -ms-linear-gradient(top, #3e779d, #65a9d7);
   background: -o-linear-gradient(top, #3e779d, #65a9d7);
   padding: 5px 5px;
   -webkit-border-radius: 8px;
   -moz-border-radius: 8px;
   border-radius: 8px;
   -webkit-box-shadow: rgba(0,0,0,1) 0 1px 0;
   -moz-box-shadow: rgba(0,0,0,1) 0 1px 0;
   box-shadow: rgba(0,0,0,1) 0 1px 0;
   text-shadow: rgba(0,0,0,.4) 0 1px 0;
   color: white;
   font-size: 14px;
   font-family: Georgia, serif;
   text-decoration: none;
   vertical-align: middle;
   }
.format-socialwall .likenomore:hover {
   border-top-color: #28597a;
   background: #28597a;
   color: #ccc;
   }
.format-socialwall .likenomore:active {
   border-top-color: #1b435e;
   background: #1b435e;
   }

.format-socialwall form.tl-commentform {
padding-top: 10px;
}

.format-socialwall #postform .fitem .felement #id_submitbutton {
margin:0px;
}

/*CSS SLIDESHOW OPTION */
.slider {
  max-width: 900px; /*Same as width of the large image*/
  position: relative;
  /*Instead of height we will use padding*/
  padding-top: 300px; /*That helps bring the labels down*/
  margin: 15px auto;
  /*Lets add a shadow*/
    border: 12px rgba(255,255,240,1) solid;
    -webkit-box-shadow: 0px 0px 5px rgba(0,0,0,.8);
    -moz-box-shadow: 0px 0px 5px rgba(0,0,0,.8);
    box-shadow: 0px 0px 5px rgba(0,0,0,.8);
}
/*Last thing remaining is to add transitions*/
.slider>img{
  position: absolute;
  left: 0px; top: 0px;
  transition: all 0.5s;
  width:100%;
  height:100%;
  margin: 0px; padding: 0px;
}
.slider input[name='slide_switch'] {
  display: none;
}
.slider label {
  /*Lets add some spacing for the thumbnails*/
  margin: 20px 0px 0px 20px;
  float:left;
  font-size: 0px;
  cursor: pointer;
  transition: all 0.5s;
  /*Default style = low opacity*/
  opacity: 0.6;
  padding:0px;
  border: 3px rgba(255,255,240,1) solid;
    -webkit-box-shadow: 0px 0px 2px rgba(0,0,0,.8);
    -moz-box-shadow: 0px 0px 2px rgba(0,0,0,.8);
  box-shadow: 0px 0px 2px rgba(0,0,0,.8);
}

.slider label img{
  display: block;
  width:50px; 
  height:30px;
  margin: 0px; padding: 0px;
}
/*Time to add the click effects*/
.slider input[name='slide_switch']:checked+label {
  border-color: #FFFB2B;
  opacity: 1;
}
/*Clicking any thumbnail now should change its opacity(style)*/
/*Time to work on the main images*/
.slider input[name='slide_switch'] ~ img {
  opacity: 0;
  transform: scale(0.9);
}
/*That hides all main images at a 110% size
On click the images will be displayed at normal size to complete the effect
*/
.slider input[name='slide_switch']:checked+label+img {
  opacity: 1;
  transform: scale(1);
}
/*Clicking on any thumbnail now should activate the image related to it*/

**Comment by beloit-rexj** [comment]
Thank you, Chris.

I have been working in Moodle 2.9. I hope that doesn't throw a wrench in things.

The changes you shared worked on my system.
![mdl 29 evolved dashboard edit button 2](https://cloud.githubusercontent.com/assets/9689055/8707632/8df80aa2-2afc-11e5-80a9-645424cd2790.png)

**Comment by robinleung** [comment]
Hi Chris,

The new code works fine in 2.8. Except for in forums. 

#editbutton .btn {float: right;}
#editbutton .singlebutton div {float:right;}

**Comment by kennibc** [comment]
Do you have a picture so I can try and fix that as well.

**Comment by robinleung** [comment]
![2015-07-15_13-01-04](https://cloud.githubusercontent.com/assets/8377859/8708567/984fc1b2-2af1-11e5-80be-5ccbbad194e0.png)

**Comment by beloit-rexj** [comment]
While this does fix the issue, there is somethng strange going on with the dock and min/max buttons (see image).
![mdl 29 evolved dashboard edit and dock button](https://cloud.githubusercontent.com/assets/9689055/8708816/ee8e7264-2b03-11e5-9ba4-3a29ebbcf6e2.png)

**Comment by kennibc** [comment]
I have uploaded a new version to Moodle.org.  It fixes these issues.  Beloit, I don't think you deleted the one line specified prior to adding in the fix.  Then once added clearing both your browser and Moodle cache is needed.
